Repository IceDBorn/filmhub, pull requests merged in 2021-05, with the labels that each got.

#32 delete-credits
  README.md
Labels: enhancement

#35 Add admin page
  Controllers/AccountController.cs
  Controllers/ActivityController.cs
  Controllers/MovieController.cs
  Controllers/QueryController.cs
  Controllers/SearchController.cs
  Controllers/SettingController.cs
  Controls/RoundButton.cs
  Controls/RoundComboBox.cs
  Controls/RoundDateTimePicker.cs
  Controls/RoundTextBox.cs
  Models/Account.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/add.png
  Resources/add_black.png
  Resources/add_hover.png
  Resources/edit.png
  Resources/edit_black.png
  Resources/edit_hover.png
  Views/Colors.cs
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.cs
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/MovieEditorUserControl.Designer.cs
  Views/MovieEditorUserControl.cs
  Views/MovieEditorUserControl.resx
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.Designer.cs
  Views/SignUpUserControl.Designer.cs
  Views/WelcomeUserControl.Designer.cs
  filmhub.csproj
Labels: bug, enhancement

#36 Add custom messagebox - replace messagebox with custom messagebox
  Controllers/AccountController.cs
  Controllers/ActivityController.cs
  Controllers/MovieController.cs
  Controllers/SearchController.cs
  Controllers/SettingController.cs
  Controls/CustomMessageBox.cs
  Models/Colors.cs
  Program.cs
  Views/ListUserControl.cs
  Views/MainPageUserControl.cs
  Views/MovieEditorUserControl.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.cs
  filmhub.csproj
Labels: enhancement

#37 Add unrate functionality
  Controllers/MovieController.cs
  Views/MovieViewerUserControl.cs
Labels: enhancement

#40 Add categories results
  Controllers/MovieController.cs
  Views/CategoriesUserControl.cs
  Views/ListUserControl.cs
Labels: enhancement

#41 Add appropriate messages for empty results on listUserControl
  Views/CategoriesUserControl.cs
  Views/ListUserControl.cs
  Views/MainForm.cs
Labels: bug, enhancement

#42 Add oscar search functionality
  Controllers/MovieController.cs
  Views/ListUserControl.cs
Labels: enhancement

#43 Add remember me functionality
  App.config
  Models/Account.cs
  Properties/Settings.Designer.cs
  Properties/Settings.settings
  Views/MainForm.cs
  Views/SignInUserControl.Designer.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.Designer.cs
  Views/SignUpUserControl.cs
Labels: enhancement

#45 Async search
  Controllers/AccountController.cs
  Controllers/ActivityController.cs
  Controllers/DatabaseController.cs
  Controllers/MovieController.cs
  Controllers/SearchController.cs
  Controllers/SettingController.cs
  Controls/CustomMessageBox.cs
  Models/Account.cs
  Views/CategoriesUserControl.Designer.cs
  Views/CategoriesUserControl.cs
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.cs
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
Labels: enhancement

#46 Fix error uploading image to new movie page
  Views/MovieEditorUserControl.cs
Labels: bug

#47 Add director search
  Controllers/SearchController.cs
Labels: enhancement

#48 Fix bugs
  Views/MainForm.cs
  Views/MovieEditorUserControl.cs
Labels: bug

#50 Save changed password into settings
  Controllers/AccountController.cs
Labels: bug

#51 Add has_oscar column to movie table
  db.sql
Labels: enhancement

#52 add movies
  db.sql
Labels: enhancement

#55 ux-ui-part
  UX-UI/UX-process/gestalt-psychology/Design Psychology.pdf
  UX-UI/UX-process/gestalt-psychology/Design-Psychology-Images/Fitts's-Law.PNG
  UX-UI/UX-process/gestalt-psychology/Design-Psychology-Images/Law-of-Proximity.PNG
  UX-UI/UX-process/gestalt-psychology/Design-Psychology-Images/Law-of-Similarity.PNG
  UX-UI/UX-process/gestalt-psychology/Design-Psychology-Images/Principle-of-Closure.PNG
  UX-UI/UX-process/gestalt-psychology/Design-Psychology-Images/Principle-of-Common-Region.PNG
  UX-UI/UX-process/journey-map/Journey-Map.PNG
  UX-UI/UX-process/methodology/UX-Design-Process-Content.png
  UX-UI/UX-process/methodology/UX-Design-Process.png
  UX-UI/UX-process/user-flow/User-Flow-Diagram.PNG
  UX-UI/UX-process/user-flow/User-Flow-Pages.PNG
  UX-UI/UX-process/user-flow/images-userflow/1.Sign In.png
  UX-UI/UX-process/user-flow/images-userflow/2.Sign Up.PNG
  UX-UI/UX-process/user-flow/images-userflow/3.Main Page.PNG
  UX-UI/UX-process/user-flow/images-userflow/4.Search.PNG
  UX-UI/UX-process/user-flow/images-userflow/5.No Result.PNG
  UX-UI/UX-process/user-flow/images-userflow/6.Rating.PNG
  UX-UI/UX-process/user-flow/images-userflow/7.User Choices.PNG
  UX-UI/UX-process/user-persona/User-Persona-Description.PNG
  UX-UI/UX-process/user-persona/User-Persona.png
  UX-UI/pies/1.PNG
  UX-UI/pies/2.PNG
  UX-UI/pies/3.PNG
  UX-UI/pies/4.PNG
  UX-UI/style-guide/style-guide.pdf
Labels: enhancement

#57 User Testing
  Testing/Filmhub_ Tasks_Video_Conclusion.pdf
  Testing/User_Testing_Results_Diagrams.pdf
  Testing/User_Testing_Results_Diagrams.xlsx
Labels: enhancement

#58 Add missing parentheses to db.sql
  db.sql
Labels: bug
