Repository IceDBorn/filmhub, pull requests merged in 2021-04, with the labels that each got.

#1 Add settings page
  MainForm.cs
  SettingsUserControl.Designer.cs
  SettingsUserControl.cs
  SettingsUserControl.resx
  filmhub.csproj
Labels: enhancement

#2 Add Login and Database controllers
  Controllers/DatabaseController.cs
  Controllers/LoginController.cs
  Models/Account.cs
  SignInUserControl.Designer.cs
  SignInUserControl.cs
  filmhub.csproj
  packages.config
Labels: enhancement

#5 Rework UI
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/account.png
  Resources/account_button.png
  Resources/account_hover.png
  Resources/back.png
  Resources/back_hover.png
  Resources/background.jpg
  Resources/background.png
  Resources/background_clear.png
  Resources/background_slogan.jpg
  Resources/home.png
  Resources/home_hover.png
  Resources/logo.png
  Resources/menu.png
  Resources/menu_hover.png
  Resources/outline_favorite_border_white_24dp.png
  Resources/outline_favorite_border_white_24dp1.png
  Resources/outline_favorite_border_white_24dp2.png
  Resources/outline_star_outline_white_24dp.png
  Resources/outline_star_outline_white_24dp1.png
  Resources/search.png
  Resources/search_button.png
  Resources/search_hover.png
  Resources/star.png
  Resources/star_empty.png
  Resources/star_empty_hover.png
  Resources/star_hover.png
  Views/Colors.cs
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  Views/MovieViewerUserControl.resx
  Views/OpenMovieUserControl.Designer.cs
  Views/OpenMovieUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SignInUserControl.Designer.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.Designer.cs
  Views/SignUpUserControl.cs
  Views/WelcomeUserControl.Designer.cs
  Views/WelcomeUserControl.cs
  filmhub.csproj
Labels: enhancement

#6 Implement star hover
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/star_empty_hover.png
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
Labels: enhancement

#7 Add custom window bar
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/close.png
  Resources/close_hover.png
  Resources/minimize.png
  Resources/minimize_hover.png
  Views/Colors.cs
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  filmhub.csproj
Labels: enhancement

#8 Add icon
  Resources/icon.ico
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainForm.resx
  filmhub.csproj
Labels: enhancement

#9 add list movies
  Views/CategoriesUserControl.cs
  Views/FavoritesUserControl.Designer.cs
  Views/FavoritesUserControl.cs
  Views/FavoritesUserControl.resx
  Views/HistoryUserControl.Designer.cs
  Views/HistoryUserControl.cs
  Views/HistoryUserControl.resx
  Views/ListUserControl.cs
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/WatchlistUserControl.Designer.cs
  Views/WatchlistUserControl.cs
  Views/WatchlistUserControl.resx
  filmhub.csproj
Labels: enhancement

#10 add designer files
  Views/CategoriesUserControl.Designer.cs
  Views/CategoriesUserControl.resx
  Views/ListMoviesUserControl.Designer.cs
  Views/ListMoviesUserControl.resx
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.resx
Labels: enhancement

#11 Remove deleted resources from app config
  filmhub.csproj
Labels: bug

#12 Implement login and logout
  Controllers/DatabaseController.cs
  Controllers/LoginController.cs
  Models/Account.cs
  Views/MainForm.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.cs
Labels: enhancement

#14 Add database creation sql file
  db.sql
Labels: enhancement

#16 Add files via upload
  privacy-policy.md
  terms-and-conditions.md
Labels: enhancement

#15 Implement image support
  Controllers/DatabaseController.cs
  Controllers/LoginController.cs
  Controllers/SearchController.cs
  Models/Account.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/default_user.png
  Views/CategoriesUserControl.Designer.cs
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.cs
  Views/ListUserControl.resx
  Views/MainForm.Designer.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/MainPageUserControl.resx
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SettingsUserControl.resx
  Views/SignInUserControl.Designer.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.Designer.cs
  Views/SignUpUserControl.cs
  filmhub.csproj
  packages.config
Labels: enhancement

#18 Use hand cursor on controls hover
  Views/CategoriesUserControl.Designer.cs
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.cs
  Views/MainForm.Designer.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SignInUserControl.Designer.cs
  Views/SignUpUserControl.Designer.cs
  Views/WelcomeUserControl.Designer.cs
Labels: enhancement

#19 Use thread on image loading to reduce latency
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
Labels: enhancement

#20 Update db schema
  Controllers/LoginController.cs
  Models/Account.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.Designer.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.Designer.cs
  Views/SignUpUserControl.cs
  db.sql
Labels: enhancement

#21 Add movie buttons
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/favorite.png
  Resources/favorite_empty.png
  Resources/favorite_empty_hover.png
  Resources/favorite_hover.png
  Resources/watched.png
  Resources/watched_empty.png
  Resources/watched_empty_hover.png
  Resources/watched_hover.png
  Resources/watchlist.png
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  filmhub.csproj
Labels: enhancement

#22 Add missing images
  Resources/watchlist_empty.png
  Resources/watchlist_empty_hover.png
  Resources/watchlist_hover.png
Labels: enhancement

#23 Add activity functionality - Improve connection to db
  Controllers/DatabaseController.cs
  Controllers/LoginController.cs
  Controllers/QueryController.cs
  Controllers/SearchController.cs
  Views/ListUserControl.cs
  Views/MainPageUserControl.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.cs
  filmhub.csproj
Labels: enhancement

#24 Add light theme
  App.config
  Controllers/LoginController.cs
  Controllers/QueryController.cs
  Program.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Properties/Settings.Designer.cs
  Properties/Settings.settings
  Resources/account_black.png
  Resources/back_black.png
  Resources/close_black.png
  Resources/dark.png
  Resources/dark_hover.png
  Resources/favorite_empty_black.png
  Resources/home_black.png
  Resources/light.png
  Resources/light_hover.png
  Resources/menu_black.png
  Resources/minimize_black.png
  Resources/search_black.png
  Resources/star_empty_black.png
  Resources/watched_empty_black.png
  Resources/watchlist_empty_black.png
  Views/CategoriesUserControl.Designer.cs
  Views/CategoriesUserControl.cs
  Views/Colors.cs
  Views/ListUserControl.Designer.cs
  Views/ListUserControl.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MainPageUserControl.cs
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.cs
  filmhub.csproj
Labels: enhancement

#25 Fix most warnings
  Properties/AssemblyInfo.cs
  Views/MainForm.cs
  Views/MainPageUserControl.Designer.cs
  Views/MovieViewerUserControl.Designer.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.Designer.cs
  Views/SignUpUserControl.cs
Labels: enhancement

#26 Change password functionality
  Controllers/AccountController.cs
  Views/SettingsUserControl.Designer.cs
  Views/SettingsUserControl.cs
  Views/SignInUserControl.cs
  Views/SignUpUserControl.cs
  filmhub.csproj
Labels: enhancement

#27 Fix miscolored and crispified images
  Resources/dark_hover.png
  Resources/light.png
  Resources/light_hover.png
  Resources/watched_empty_hover.png
Labels: bug

#29 update read me
  README.md
Labels: enhancement

#30 Update README.md
  README.md
Labels: enhancement

#31 Code cleanup
  Controllers/AccountController.cs
  Controllers/MovieController.cs
  Controllers/SettingController.cs
  Models/Account.cs
  Models/Movie.cs
  Views/MainPageUserControl.cs
  Views/MovieViewerUserControl.cs
  Views/SettingsUserControl.cs
  filmhub.csproj
Labels: bug, enhancement
